log_levels:
  agent: 0
  camp: 0
  init: 0
  flood: 0
  link: 0

# Set to 100 to scale down the population by 100 and increase the execution time.
optimisations:
  hasten: 100

spawn_rules:
  flood_driven_spawning: True
  flood_zone_spawning_only: True
  conflict_zone_spawning_only: False
  take_from_population: True
  flood_driven_spawning:
    flood_spawn_mode: "pop_ratio"
    displaced_per_flood_day: [0.01,0.01,0.02,0.05,0.09]

move_rules:
  max_flood_level: 4
  flood_rules:
    flood_movechances: [0.1,0.1,0.1,0.1,0.0]
    flood_loc_weights: [0.0,0.1,0.2,0.0,0.0]