vary_parameters_range:
    # <parameter_name:>
    #   range: [<lower value>,<upper value>] 
    max_move_speed:
        range: [100, 500]
    max_walk_speed:
        range: [10, 100]
    max_crossing_speed:
        range: [10, 50]
    foreign_weight:
        range: [1.0, 10.0]
    camp_weight:
        range: [1.0, 10.0]
    conflict_weight:
        range: [0.1, 1.0]
    conflict_movechance:
        range: [0.1, 1.0] 
    camp_movechance:
        range: [0.0, 0.1]
    default_movechance:
        range: [0.1, 1.0]
    idpcamp_movechance:
        range: [0.1, 1.0]

selected_vary_parameters: ["max_move_speed", "max_walk_speed"]

distribution_type: "Uniform" # Uniform, DiscreteUniform

# this will be used in case of calling VVP_QoI
polynomial_order: 2

# this will be used in case of calling VVP_LoR
polynomial_order_range:
  start: 1
  end: 3
  step: 1

# template file should be available in FabFlee/templates folder
encoder_template_fname : "simsetting.template"
encoder_delimiter: "$"
encoder_target_filename: "simsetting.yml"

decoder_output_column: "Total error"


# sampler_name: str
#   Samplers in the context of EasyVVUQ are classes that generate
#   sequences of parameter dictionaries.
#   available sampler: [SCSampler,PCESampler]
#
#   SCSampler: Stochastic Collocation sampler
#   PCESampler : Polynomial Chaos Expansion
#   ---------------------------------------------------------------
#   TODO : add other available easyvvuq sampler to the code
#   LHCSampler : Latin hypercube sampling
#   BasicSweep :
#   MultiSampler : Expects one or more samplers
#   ReplicaSampler:
#   QMCSampler : Quasi Monte Carlo sampler
#   MCSampler: Monte Carlo sampler
#   RandomSampler : 
sampler_name: "PCESampler"


# quadrature_rule : char
#     The quadrature method, default is Gaussian "G".
#     "G" -> Gaussian , "C" -> Clenshaw_Curtis
quadrature_rule: "G"

# sparse : bool
#             If True use sparse grid instead of normal tensor product grid,
#             default is False
sparse: False

# growth: bool
#     Sets the growth rule to exponential for Clenshaw Curtis quadrature,
#     which makes it nested, and therefore more efficient for sparse grids.
#     Default is False.
growth: False

# midpoint_level1: bool,  ----- ONLY USED FOR SCSampler ------
#     determines how many points the 1st level of a sparse grid will have.
#     If midpoint_level1 = True, order 0 quadrature will be generated
midpoint_level1: False

# dimension_adaptive: bool, ----- ONLY USED FOR SCSampler ------
#     determines wether to use an insotropic sparse grid, or to adapt
#     the levels in the sparse grid based on a hierachical error measure
dimension_adaptive: False

# ------- NOTE ------------
# if you set quadrature_rule="C", then you need to make sure
#     sparse=True
#     growth=True
#     midpoint_level1=True
